resolve conda astropy <-> libpng pkg conflict
    UnsatisfiableError: The following specifications were found to be in
    conflict:

      - astropy 1.2.1 np111py27_0
      - libpng 1.6.22 0